# Generated by Django 5.1.6 on 2025-02-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='images/')),
                ('country', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('name_father', models.CharField(max_length=30)),
                ('surname_father', models.CharField(max_length=50)),
                ('name_mother', models.CharField(max_length=30)),
                ('surname_mother', models.CharField(max_length=50)),
                ('siblings', models.PositiveIntegerField(default=0)),
                ('degree', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], max_length=15)),
                ('previous_school', models.CharField(max_length=200)),
                ('status_of_studies', models.CharField(choices=[('In process', 'In process'), ('Finished', 'Finished')], max_length=15)),
                ('graduation', models.DateTimeField()),
                ('study_country', models.CharField(max_length=50)),
                ('study_address', models.CharField(max_length=100)),
                ('study_language', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
                ('financial_support', models.BooleanField(default=False)),
                ('essay', models.CharField(blank=True, max_length=5000, null=True)),
                ('diploma', models.FileField(upload_to='')),
                ('documents', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
