# Generated by Django 5.1.6 on 2025-02-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_documents_card_remove_cards_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='documents',
        ),
        migrations.AlterField(
            model_name='documents',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cards.cards'),
        ),
    ]
