# Generated by Django 5.1.6 on 2025-02-16 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
