# Generated by Django 5.1.6 on 2025-02-25 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_documents_cards_wanted_countries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='cards.cards'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cards',
            name='documents',
        ),
        migrations.AddField(
            model_name='cards',
            name='documents',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
